- name: Who am I
  run: aws sts get-caller-identity

- name: Check bucket exists
  run: aws s3api head-bucket --bucket "${{ secrets.S3_BUCKET }}"

- name: Try listing bucket
  run: aws s3 ls "s3://${{ secrets.S3_BUCKET }}/"

name: Deploy to S3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-s3-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      BUILD_DIR: dist

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: aws s3 sync "$BUILD_DIR" "s3://${{ secrets.S3_BUCKET }}" --delete

      - name: Set Cache-Control for HTML
        run: |
          aws s3 cp "s3://${{ secrets.S3_BUCKET }}/" "s3://${{ secrets.S3_BUCKET }}/" \
            --recursive --exclude "*" --include "*.html" \
            --metadata-directive REPLACE \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"
